[package]
name = "diskedit"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
clap = { version = "4.3.17", features = ["derive"] }
bootsector = "0.2.0"
gpt = "3.1.0"
uuid = "1.4.1"
